/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Custodio_OOPCOMP121
 */
public class Menu extends javax.swing.JFrame {
  
    
    public Menu() {
        
        
        initComponents();
        
        setBounds(188,77,1025,619);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bow = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        swordbutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/elf_bow_1_-removebg-preview.png"))); // NOI18N
        bow.setContentAreaFilled(false);
        bow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowActionPerformed(evt);
            }
        });
        getContentPane().add(bow, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 130, 460));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shield_flag_knight_man__GB_Kho_1_-removebg-preview.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 130, 450));

        swordbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragon_slayer___이_개컨_1_-removebg-preview.png"))); // NOI18N
        swordbutton.setContentAreaFilled(false);
        swordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swordbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(swordbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 470));

        jButton4.setText("Inventory");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sun Empire_ Plateau Marketplace, Philip V_.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sun Empire_ Plateau Marketplace, Philip V_.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        First first = new First();
        first.setVisible(true);
        this.setVisible(false);
        System.out.println(getBounds());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void swordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swordbuttonActionPerformed
        Second second = new Second();
        second.setVisible(true);
        this.setVisible(false);
        
        DBConnection.init();
        Connection c = DBConnection.getConnection();
        PreparedStatement ps;
        try {
            ps = c.prepareStatement("Select * from weapon_shop.weapon_store Where class = 'Sword'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
               
                second.model1.addRow(new Object []{false,rs.getString("weapong_id"),rs.getString("name"), rs.getString("type"), rs.getString("price")});
            }        
            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_swordbuttonActionPerformed

    private void bowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowActionPerformed
        Third third = new Third();
        third.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fourth fourth = new fourth();
        fourth.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bow;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton swordbutton;
    // End of variables declaration//GEN-END:variables
}
